site_name: Nginx Docker Docs
site_description: Documentación del Servidor Nginx en Docker
site_url: https://jonhbrz.github.io/Servidor_Nginx/
site_author: Jonathan
theme:
  name: darkly
nav:
  - Inicio: index.md
  - Instalación: instalacion.md
  - Configuración: configuracion.md
  - Múltiples Apps: apps-multiples.md